foodgram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("posts.urls")),
    path("admin/", admin.site.urls),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import include, path

from . import views


urlpatterns = [ 
    path("", views.index, name="index"),
    path("404/", views.page_not_found, name="page_not_found"),
    path("500/", views.server_error, name="server_error"), 
    path("profile/<str:username>/", views.profile, name="profile"), 
    path("new/", views.new_recipe, name="new_recipe"), 
    path(
        "purchases/<int:id>/", 
        views.api_purchases_delete, name="purchases_delete"),
    path("favorites/", views.api_favorites_add, name="favorites_add"),
    path(
        "favorites/<int:id>/", 
        views.api_favorites_delete, name="favorites_delete"),
    path("favor/", views.favorites, name="favorites"), 
    path("subscriptions/", views.api_follow_add, name="follow_add"),
    path(
        "subscriptions/<str:id>/", 
        views.api_follow_delete, name="follow_delete"),
    path("followers/", views.follow, name="followers"),
    path("ingredients/", views.ingredients),
    path("shop/", views.purchases, name="my_purchases"),
    path("shop/download/", views.purchases_download, name="download"),
    path('about/', views.AboutPage.as_view(), name="about"),
    path('technology/', views.TechnologyPage.as_view(), name="technology"),
    path('brand/', views.BrandPage.as_view(), name="brand"),   
    path("<str:username>/<int:recipe_id>/", views.recipe_view, name="recipe"), 
    path(
        "<str:username>/<int:recipe_id>/edit/", 
        views.recipe_edit, name="recipe_edit"), 
    path("purchases/", views.api_purchases_add, name="purchases_add"),
] 

posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.core.validators import MinValueValidator

User = get_user_model() 

 
class Ingredient(models.Model): 
    title = models.TextField(verbose_name="название") 
    dimension = models.TextField(verbose_name="мера") 
    
    def __str__(self): 
        return self.title
    
    class Meta: 
        verbose_name = "Ингредиент"


class Tag(models.Model): 
    title = models.CharField(verbose_name="тег", max_length=20) 
    color = models.CharField(verbose_name="цвет", max_length=20) 
    name = models.CharField(verbose_name="имя тега", max_length=20)
    
    def __str__(self): 
        return self.name

    class Meta: 
        verbose_name = "Тэг"


class Recipe(models.Model): 
    name = models.CharField(verbose_name="имя", max_length=50) 
    description = models.TextField(verbose_name="описание") 
    pub_date = models.DateTimeField(
        verbose_name="дата публикации", auto_now_add=True) 

    author = models.ForeignKey(
        User, on_delete=models.CASCADE, 
        related_name="authors", 
        verbose_name="автор"
    ) 
    
    image = models.ImageField(upload_to="posts/", blank=True, null=True)
    time = models.PositiveIntegerField(
        verbose_name="время", validators=[MinValueValidator(1, message = 'ппц')]
        ) 
    ingredient = models.ManyToManyField(
        Ingredient, through="Number", through_fields=("recipe", "ingredient"), 
        related_name="recipes"
        )
    tags = models.ManyToManyField(Tag)


    class Meta: 
        ordering = ["-pub_date"]
        verbose_name = "Рецепт"
     

    def __str__(self): 
        return self.name


class Number(models.Model): 
    recipe = models.ForeignKey(
        Recipe , on_delete=models.CASCADE, 
        related_name="numbers", verbose_name="рецепт"
        )
    ingredient = models.ForeignKey(
        Ingredient, on_delete=models.CASCADE, 
        related_name="numbers", verbose_name="ингредиент"
        )
    amount = models.IntegerField(validators=[MinValueValidator(1)])

    def __str__(self):
        return str(self.amount)
    
    class Meta: 
        verbose_name = "Число"


class Favorite(models.Model): 
    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE, 
        related_name="favorite", verbose_name="рецепт"
        )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE, 
        related_name="follower",
        verbose_name="пользователь"
        )
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        constraints = [models.UniqueConstraint(
            fields= ["user", "recipe"], name="favorite_unique")]
        verbose_name = "Избранное"
        ordering = ("-created",)


class Purchase(models.Model): 
    recipe = models.ForeignKey(
        Recipe , on_delete=models.CASCADE,  
        related_name="purchase", verbose_name="рецепт"
        )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE, 
        related_name="owner",
        verbose_name="пользователь"
        )
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        constraints = [models.UniqueConstraint(
            fields= ["user", "recipe"], name="purchase_unique")]
        verbose_name = "Покупки"
        ordering = ("-created",)


class Follow(models.Model): 
    
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="follow",
        verbose_name="подписчик"
        )

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="following",
        verbose_name="на_кого_подписались"
        )
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        constraints = [models.UniqueConstraint(
            fields= ["user", "author"], name="follow_unique")]
        verbose_name = "Подписки"
        ordering = ("-created",)
        

templates/about.html
{% extends "base.html" %} {% load static %} {% block css %}
<link rel="stylesheet" href="{% static 'pages/single.css' %}" /> {% endblock %} {% block content %} {% load user_filters %}

<main class="main container">
    <div class="single-card" data-id={{ recipe.id }} data-author={{ recipe.author }}>
        <img class="single-card__image" src="{% static 'images/me.jpg' %}" />
        <div class="single-card__info">
            <div class="single-card__section">
                <h3 class="single-card__section-title">Об авторе</h3>
                <p class="single-card__section-text">
                    ________________________________________________________________________________________________
                </p>

                <p class="single-card__section-text">
                    Добрый день, меня зовут Константин!
                </p>
                <p class="single-card__section-text">
                    Я начинающий junior python разработчик
                </p>
                <p class="single-card__section-text">
                    Этот сайт я сделал для дипломной работы в Yandex.Praktikum
                </p>
                <p class="single-card__section-text">
                    Мой GitHub с другими моими проектами: https://github.com/zerobubus/
                </p>
                <p class="single-card__section-text">
                    _________________________________________________________________________________________________
                </p>
            </div>
        </div>
    </div>
</main>

{% endblock %}

templates/authorRecipe.html
{% extends "base.html" %} {% load static %} {% block css %}
<link rel="stylesheet" href="{% static 'pages/index.css' %}"> {% endblock %} {% block content %} {% load user_filters %}
<main class="main container">
    <div class="main__header">
        <h1 class="main__title">{{ profile.get_full_name }}</h1>
        <ul class="tags">
            {% include "includes/tags.html" with tags=tags %}
        </ul>

    </div>
    {% if user.is_authenticated %}
    {% if user != profile %}
    <div class="author-subscribe" data-author={{ profile }}>
        {% if not follow %}
        <p style="padding: 0 0 2em 0;">
            <button class="button button_style_light-blue button_size_subscribe" name="subscribe" data-out>Подписаться на автора</button>
        </p>
        {% else %}
        <p style="padding: 0 0 2em 0;">
            <button class="button button_style_light-blue button_size_subscribe" name="subscribe">Отписаться от автора</button>
        </p>
        {% endif %}
    </div>
    {% endif %}
    {% endif %}

    <div class="card-list">
        {% for post in page %}
        <div class="card" data-id={{ post.id }}>
            {% load thumbnail %} {% thumbnail post.image "500x500" crop="center" upscale=True as im %}
            <a href="{% url 'recipe' post.author.username post.id %}" class="link" ><img src="{{ im.url }}" alt="{{ im.name }}" class="card__image"></a>
            {% endthumbnail %}
            <div class="card__body">
                <a class="card__title link" href="{% url 'recipe' post.author.username post.id %}" >{{ post.name }}</a>
                <ul class="card__items">
                    {% for tag in post.tags.all %}

                    <li class="card__item"><span class="badge badge_style_{{ tag.color }}">{{ tag }}</span></li>

                    {% endfor %}
                </ul>
                <div class="card__items card__items_column">
                    <p class="card__text"><span class="icon-time"></span> {{ post.time }} мин.</p>
                    <p class="card__text"><span class="icon-user"></span> <a href="{% url 'profile' post.author.username %}" style="color: black">{{ post.author }}</a></p>
                </div>
            </div>
            <div class="card__footer">
                {% if user.is_authenticated %}
                {% distinct post.purchase.all as items %} {% if not items %}
                <button class="button button_style_light-blue" name="purchases" data-out><span class="icon-plus button__icon"></span>Добавить покупки</button>
                {% else %}
                <button class="button button_style_light-blue" name="purchases"><span class="icon-plus button__icon"></span>Убрать из покупок</button>
                {% endif %} {% distinct post.favorite.all as items %} {% if not items %}
                <button class="button button_style_none" name="favorites" data-out><span class="icon-favorite icon-favorite_big"></span></button>
                {% else %}
                <button class="button button_style_none" name="favorites"><span class="icon-favorite icon-favorite_active"></span></button>
                {% endif %}
                {% endif %}

            </div>

        </div>
        {% endfor %}
    </div>


    {% if page.has_other_pages %} {% include "includes/paginator.html" with items=page paginator=paginator %} {% endif %}
</main>
{% endblock %} {% block style %}

<script src="{% static 'js/components/MainCards.js' %}"></script>
<script src="{% static 'js/components/Purchases.js' %}"></script>
<script src="{% static 'js/components/Favorites.js' %}"></script>
<script src="{% static 'js/components/Subscribe.js' %}"></script>
<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/AuthorRecipe.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>

<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'authorRecipe.js' %}"></script>

{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">

<head>
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Рецепты</title>
    {% block css %} {% endblock %}
</head>

<body class="body">
    <header class="header">
        {% include "includes/nav.html" %}
    </header>


    {% block content %} {% endblock %}


    <footer class="footer">
        {% include "includes/footer.html" %}
    </footer>

</body>
{% block style %} {% endblock %}

</html>

templates/brand.html
{% extends "base.html" %} {% load static %} {% block css %}
<link rel="stylesheet" href="{% static 'pages/single.css' %}" />
{% endblock %} {% block content %} {% load user_filters %}

<main class="main container">
  <div class="single-card__info">
    <div class="single-card__section">
      <h3 class="single-card__section-title">О сайте</h3>
      <p class="single-card__section-text">
        __________________________________________________________________________________________________________________________________________
      </p>

      <p class="single-card__section-text">Добро пожаловать на сайт!</p>
      <p class="single-card__section-text">
        Здесь Вы можете делиться своими рецептами и находить новые.
      </p>
      <p class="single-card__section-text">
        Рецепты, короторые Вам понравились , можете добавить в избранное(нажать
        на звездочку)
      </p>
      <p class="single-card__section-text">
        Также можете подписаться на авторов и следить за новыми рецептами,
        которые они опубликуют.
      </p>
      <p class="single-card__section-text">
        Можно добавить рецепты в список покупок и потом сформировать список с
        ингредиентами для похода в магазин(нажать скачать список)
      </p>
      <p class="single-card__section-text">
        ___________________________________________________________________________________________________________________________________________
      </p>
    </div>
  </div>
</main>
{% endblock %}

templates/favourite.html
{% extends "base.html" %} {% load static %} {% block css %}
<link rel="stylesheet" href="{% static 'pages/index.css' %}"> {% endblock %} {% block content %} {% load user_filters %}

<main class="main container">
    <div class="main__header">
        <h1 class="main__title">Избранное</h1>
        <ul class="tags">
            {% include "includes/tags.html" with tags=tags %}
        </ul>
    </div>
    <div class="card-list">
        {% for post in page %}

        <div class="card" data-id={{ post.recipe.id }} data-author={{ post.recipe.author }}>
            {% load thumbnail %} {% thumbnail post.recipe.image "960x339" crop="center" upscale=True as im %}
            <a href="{% url 'recipe' post.recipe.author.username post.recipe.id %}" class="link"><img src="{{ im.url }}" alt="{{ im.name }}" class="card__image"></a>
            {% endthumbnail %}

            <div class="card__body">
                <a class="card__title link" href="{% url 'recipe' post.recipe.author.username post.recipe.id %}" >{{ post.recipe }}</a>
                <ul class="card__items">
                    {% for tag in post.recipe.tags.all %}

                    <li class="card__item"><span class="badge badge_style_{{ tag.color }}">{{ tag }}</span></li>

                    {% endfor %}
                </ul>
                <div class="card__items card__items_column">

                    <p class="card__text"><span class="icon-time"></span> {{ post.recipe.time }} мин.</p>
                    {% if post.recipe.author.get_full_name %}
                    <p class="card__text"><span class="icon-user"></span> <a href="{% url 'profile' post.recipe.author.username %}" style="color: black">{{ post.recipe.author.get_full_name }}</a></p>
                    {% else %}
                    <p class="card__text"><span class="icon-user"></span> <a href="{% url 'profile' post.recipe.author.username %}" style="color: black">{{ post.recipe.author.username }}</a></p>
                    {% endif %}
                </div>
            </div>
            <div class="card__footer">
                {% distinct post.recipe.purchase.all as items %} {% if not items %}
                <button class="button button_style_light-blue" name="purchases" data-out><span class="icon-plus button__icon"></span>Добавить покупки</button>
                {% else %}
                <button class="button button_style_light-blue" name="purchases"><span class="icon-plus button__icon"></span>Убрать из покупок</button>
                {% endif %}

                <button class="button button_style_none" name="favorites"><span class="icon-favorite icon-favorite_active"></span></button>

            </div>
        </div>
        {% endfor %}
    </div>
    {% if page.has_other_pages %} {% include "includes/paginator.html" with items=page paginator=paginator %} {% endif %}
</main>

{% endblock %} {% block style %}

<script src="{% static 'js/components/MainCards.js' %}"></script>

<script src="{% static 'js/components/Purchases.js' %}"></script>
<script src="{% static 'js/components/Favorites.js' %}"></script>
<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/CardList.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>

<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'favorite.js' %}"></script>
{% endblock %}

templates/formChangeRecipe.html
{% extends "base.html" %} 
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'pages/form.css' %}">
{% endblock %}
{% block content %}
{% load user_filters %}
      <main class="main container">
        <div class="main__header">
            <h1 class="main__title">Редактирование рецепта</h1>
        </div>
        <div class="form-container">
            <form class="form" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form__group">
                    <label for="id_name" class="form__label">Название рецепта</label>
                    <div class="form__field-group">
                        <input value="{{ form.name.value|default_if_none:'' }}" type="text" id="id_name" name="name" class="form__input">
                        <span class="form__error"></span>
                    </div>
                </div>
                
        
                <div class="form__group">
                    <p class="form__label">Теги</p>
                    <div class="form__field-group">
                      <div class="tags">
                        {% for tag in form.fields.tags.choices.queryset %}
                          <div class="tags__item">
                            <input 
                              type="checkbox" 
                              name="tags" 
                              id="id_{{ tag.name }}"
                              class="tags__checkbox tags__checkbox_style_{{ tag.color }}"
                              value="{{ tag.pk }}"
                              {% if tag.pk in form.tags.value %}checked{% endif %}>
                            <label for="id_{{ tag.name }}" class="tags__label">{{ tag.name }}</label>
                          </div>
                        {% endfor %}
                      </div>
                      <span class="form__error">{{ form.tags.errors }}</span>
                    </div>
                  </div>
             
                  <div class="form__group">
                    <label for="nameIngredient" class="form__label">Ингредиенты</label>
    ​
                    <div class="form__field-group">
                        <div class="form__field-group-ingredientes">
                            <div class="form__dropdown">
                                <input type="text" id="nameIngredient" class="form__input">
                                <div class="form__dropdown-items"></div>
                            </div>
                            <input type="number" id="cantidad" class="form__input" min="0">
                            <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
                        </div>
                        <div class="form__field-group-ingredientes-container">
                            {% for amount in amounts %}
                                <div class="form__field-item-ingredient" id="ing_{{ forloop.counter }}">
                                    <span> {{ amount.ingredient }} {{ amount }} {{ amount.ingredient.dimension }}</span>
                                    <span class="form__field-item-delete"></span>
                                    <input id="nameIngredient_{{ forloop.counter }}" name="nameIngredient_{{ forloop.counter }}" type="hidden" value="{{ ingredient.ingredient.title }}">
                                    <input id="valueIngredient_{{ forloop.counter }}" name="valueIngredient_{{ forloop.counter }}" type="hidden" value="{{ ingredient.quantity }}">
                                    <input id="unitsIngredient_{{ forloop.counter }}" name="unitsIngredient_{{ forloop.counter }}" type="hidden" value="{{ ingredient.ingredient.dimension }}">
                                </div>
                            {% endfor %}
                        </div>
                        <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                        <span class="form__error">{{ form.ingredients.errors }}</span>
                    </div>
                </div>
    
            
                  
                <div class="form__group">
                    <label for="id_time" class="form__label">Время приготовления</label>
                    <div class="form__field-group form__field-group_time">
                        <input type="number" value="{{ form.time.value|default_if_none:'' }}"  id="id_time" name="time" class="form__input">
                        <label for="id_time" class="form__label">минут</label>
                        <span class="form__error">{{ form.time.errors }}</span>
                    </div>
                </div>
                <div class="form__group">
                    <label for="id_description" class="form__label">Описание</label>
                    <div class="form__field-group">
                        <textarea name="description"  id="id_description" rows="8" class="form__textarea">{{ form.description.value|default_if_none:'' }}</textarea>
                        <span class="form__error"></span>
                    </div>
                </div>
                <div class="form__group">
                    <span class="form__label">Загрузить фото</span>
                    <div class="form__field-group">
                        <input type="file" name="image" id="id_image">{{ form.image.value|default_if_none:'' }}
                        <span class="form__error"></span>{{ form.image.errors }}
                    </div>
                </div>
                <div class="form__footer">
                    <button type="submit" class="button button_style_blue">Редактировать рецепт</button>
                </div>
            </form>
        </div>
</main>

{% endblock %}

{% block style %}

<script src="{% static 'js/config/config.js' %}"></script>  
<script src="{% static 'js/components/Header.js' %}"></script> 
<script src="{% static 'js/utils/debouncing.js' %}"></script> 
<script src="{% static 'js/api/Api.js' %}"></script>  
<script src="{% static 'formRecipe.js' %}"></script> 
{% endblock %}

templates/formRecipe.html
{% extends "base.html" %} 
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'pages/form.css' %}">
{% endblock %}
{% block content %}
{% load user_filters %}

      <main class="main container">
        <div class="main__header">
            <h1 class="main__title">Создание рецепта</h1>
        </div>
        <div class="form-container">
            <form class="form" method="post" action="{% url 'new_recipe' %}" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form__group">
                    <label for="id_name" class="form__label">Название рецепта</label>
                    <div class="form__field-group">
                        <input value="{{ form.name.value|default_if_none:'' }}" type="text" id="id_name" name="name" class="form__input" >
                        <span class="form__error">{{ form.name.errors }}</span>
                    </div>
                </div>
                
                
                <div class="form__group">
                    <p class="form__label">Теги</p>
                    <div class="form__field-group">
                      <div class="tags">
                        {% for tag in form.fields.tags.choices.queryset %}
                          <div class="tags__item">
                            <input 
                              type="checkbox" 
                              name="tags" 
                              id="id_{{ tag.name }}"
                              class="tags__checkbox tags__checkbox_style_{{ tag.color }}"
                              value="{{ tag.pk }}"
                              {% if tag.pk in form.tags.value %}checked{% endif %}>
                            <label for="id_{{ tag.name }}" class="tags__label">{{ tag.name }}</label>
                          </div>
                        {% endfor %}
                      </div>
                      <span class="form__error">{{ form.tags.errors }}</span>
                    </div>
                  </div>
             
                     
                <div class="form__group">
                    <label for="nameIngredient" class="form__label">Ингредиенты</label>
                    <div class="form__field-group">
                        <div class="form__field-group-ingredientes">
                            <div class="form__dropdown">
                                <input type="text" id="nameIngredient" class="form__input" >
                                <div class="form__dropdown-items"></div>
                            </div>
                            <input type="number" id="cantidad" class="form__input" min="0">
                            <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
                        </div>
                        <div class="form__field-group-ingredientes-container">
    
                        </div>
                        <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                        <span class="form__error">{{ error }}</span>
                    </div>
                </div>
                <div class="form__group">
                    <label for="id_time" class="form__label">Время приготовления</label>
                    <div class="form__field-group form__field-group_time">
                        <input type="number" value="{{ form.time.value|default_if_none:'' }}" id="id_time" name="time" class="form__input" required>
                        <label for="id_time" class="form__label">минут</label>
                        <span class="form__error">{{ form.time.errors }}</span>
                    </div>
                </div>
                <div class="form__group">
                    <label for="id_description" class="form__label">Описание</label>
                    <div class="form__field-group">
                        <textarea name="description" id="id_description" rows="8" class="form__textarea" required>{{ form.description.value|default_if_none:'' }}</textarea>
                        <span class="form__error"></span>
                    </div>
                </div>
                <div class="form__group">
                    <span class="form__label">Загрузить фото</span>
                    <div class="form__field-group">
                        <input type="file" name="image" id="id_image" required>{{ form.image.value|default_if_none:'' }}
                        <span class="form__error"></span>
                    </div>
                </div>
                <div class="form__footer">
                    <button type="submit" class="button button_style_blue">Создать рецепт</button>
                </div>
            </form>
        </div>
    
</main>
{% endblock %}

{% block style %}

<script src="{% static 'js/config/config.js' %}"></script>  
<script src="{% static 'js/components/Header.js' %}"></script> 
<script src="{% static 'js/utils/debouncing.js' %}"></script> 
<script src="{% static 'js/api/Api.js' %}"></script>  
<script src="{% static 'formRecipe.js' %}"></script> 
{% endblock %}

templates/indexAuth.html
{% extends "base.html" %} {% load static %} {% block css %}
<link rel="stylesheet" href="{% static 'pages/index.css' %}"> {% endblock %} {% block content %} {% load user_filters %}
<main class="main container">
    <div class="main__header">
        <h1 class="main__title">Рецепты</h1>
        <ul class="tags">

            {% include "includes/tags.html" with tags=tags %}

        </ul>
    </div>
    <div class="card-list">
        {% for post in page %}

        <div class="card" data-id={{ post.id }}>
            {% load thumbnail %} {% thumbnail post.image "500x500" crop="center" upscale=True as im %}

            <a href="{% url 'recipe' post.author.username post.id %}" class="link"><img src="{{ im.url }}" alt="{{ im.name }}" class="card__image"></a>
            {% endthumbnail %}

            <div class="card__body">
                <a class="card__title link" href="{% url 'recipe' post.author.username post.id %}">{{ post.name }}</a>
                <ul class="card__items">
                    {% for tag in post.tags.all %}

                    <li class="card__item"><span class="badge badge_style_{{ tag.color }}">{{ tag }}</span></li>

                    {% endfor %}
                </ul>
                <div class="card__items card__items_column">

                    <p class="card__text"><span class="icon-time"></span> {{ post.time }} мин.</p>

                    <p class="card__text"><span class="icon-user"></span> <a href="{% url 'profile' post.author.username %}" style="color: black">{{ post.author}}</a></p>
                </div>
            </div>
            <div class="card__footer">
                {% if user.is_authenticated %}
                {% distinct post.purchase.all as items %} {% if not items %}
                <button class="button button_style_light-blue" name="purchases" data-out><span class="icon-plus button__icon"></span>Добавить покупки</button>
                {% else %}
                <button class="button button_style_light-blue" name="purchases"><span class="icon-plus button__icon"></span>Убрать из покупок</button>
                {% endif %}
                {% endif %}

            </div>
        </div>
        {% endfor %}
    </div>
    {% if page.has_other_pages %} {% include "includes/paginator.html" with items=page paginator=paginator %} {% endif %}
</main>
{% endblock %} {% block style %}
<script src="{% static 'js/components/MainCards.js' %}"></script>

<script src="{% static 'js/components/Purchases.js' %}"></script>
<script src="{% static 'js/components/Favorites.js' %}"></script>

<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/CardList.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>

<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'indexAuth.js' %}"></script>
{% endblock %}